spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/covid_db
        username: postgres
        password: postgres
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        hibernate :
            ddl-auto: create
    liquibase:
        change-log: db/changelog/db.changelog-master.yaml

management:
  endpoints:
    jmx:
      exposure:
        include: info,health,beans,metrics,endpoints,mappings
    web:
      exposure:
        include: health,info,prometheus,metrics

server:
  port: 12037
logging:
  level:
    io:
      micrometer: DEBUG
    org:
      springframework:
        security: DEBUG
